//! Raw libmobi FFI bindings generated by bindgen at build time.
//!
//! Do not consume this module directly. Use the safe wrappers in the parent
//! `mobi` module instead — everything in here is `unsafe extern "C"`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::useless_transmute)]

include!(concat!(env!("OUT_DIR"), "/libmobi_bindings.rs"));
