//! MOBI / AZW / AZW3 (KF8) parser backed by libmobi.
//!
//! This module is gated behind the `mobi` cargo feature (opt-in). libmobi is
//! dynamically linked (LGPL v3+); the library is located at build time via
//! pkg-config or the `LIBMOBI_INCLUDE_DIR` / `LIBMOBI_LIB_DIR` env vars.
//!
//! The public surface is shaped for the Folio BookFormat adapter
//! (see ROADMAP #34): open a file, read metadata, reconstruct the rawml, walk
//! markup/flow/resource parts, and extract the cover.

mod adapter;
mod ffi;

pub use adapter::{
    extract_cover, get_chapter_content, get_chapter_list, get_chapter_word_counts,
    parse_mobi_metadata, MobiMetadata,
};

use std::ffi::{CStr, CString};
use std::marker::PhantomData;
use std::path::Path;
use std::ptr::{self, NonNull};
use std::slice;

use crate::error::{FolioError, FolioResult};

/// A parsed MOBI/AZW/AZW3 file. Releases the underlying `MOBIData` on drop.
pub struct MobiBook {
    handle: *mut ffi::MOBIData,
}

impl MobiBook {
    /// Parse a MOBI/AZW/AZW3 file from disk.
    ///
    /// Paths are required to be valid UTF-8. On Unix this rules out the
    /// (rare) arbitrary-byte filenames that `Path` technically supports; for
    /// Folio that's fine because imports are copied into the app-managed
    /// library directory (`~/Documents/folio/...`) where the filenames are
    /// generated by us and are always UTF-8. Rejecting non-UTF-8 here is
    /// preferable to silently corrupting the path with `U+FFFD`
    /// replacement, which would make libmobi open the wrong file — or no
    /// file at all — with no obvious error.
    pub fn open(path: &Path) -> FolioResult<Self> {
        let path_str = path.to_str().ok_or_else(|| {
            FolioError::InvalidInput(format!("MOBI path is not valid UTF-8: {}", path.display()))
        })?;
        let c_path = CString::new(path_str.as_bytes())
            .map_err(|_| FolioError::InvalidInput("MOBI path contained a NUL byte".into()))?;

        // SAFETY: `mobi_init` returns either a valid heap pointer or null.
        // `mobi_load_filename` reads the path string we keep alive until
        // it returns. We free the handle on any error path.
        unsafe {
            let handle = ffi::mobi_init();
            if handle.is_null() {
                return Err(FolioError::Internal(
                    "libmobi failed to allocate MOBIData".into(),
                ));
            }

            let rc = ffi::mobi_load_filename(handle, c_path.as_ptr());
            if rc != ffi::MOBI_RET_MOBI_SUCCESS {
                ffi::mobi_free(handle);
                return Err(map_mobi_ret(
                    rc,
                    &format!("libmobi failed to open {}", path.display()),
                ));
            }

            Ok(Self { handle })
        }
    }

    /// Title from the EXTH metadata record, preferred over the PalmDB
    /// "name" field because it's always UTF-8 and avoids libmobi's iconv
    /// code path (which crashes on macOS Tahoe arm64 at process exit).
    pub fn title(&self) -> Option<String> {
        // SAFETY: `handle` is valid for the lifetime of `self`;
        // `mobi_meta_get_title` returns either null or a heap-allocated
        // NUL-terminated UTF-8 string that the caller must `free()`.
        unsafe { take_c_string(ffi::mobi_meta_get_title(self.handle)) }
    }

    /// Author from EXTH metadata. Returns `None` when the EXTH record is
    /// missing.
    pub fn author(&self) -> Option<String> {
        // SAFETY: as above, paired with the matching `free()`.
        unsafe { take_c_string(ffi::mobi_meta_get_author(self.handle)) }
    }

    /// Language tag from EXTH (BCP-47 style, e.g. "en", "de-DE"). None if
    /// the field is missing.
    pub fn language(&self) -> Option<String> {
        // SAFETY: libmobi returns a heap-allocated NUL-terminated UTF-8
        // string that the caller must `free()`.
        unsafe { take_c_string(ffi::mobi_meta_get_language(self.handle)) }
    }

    /// Long-form description / synopsis from EXTH. Often contains HTML.
    pub fn description(&self) -> Option<String> {
        unsafe { take_c_string(ffi::mobi_meta_get_description(self.handle)) }
    }

    /// ISBN from EXTH. Not normalized — the caller should run it through
    /// [`crate::isbn`] if a canonical form is needed.
    pub fn isbn(&self) -> Option<String> {
        unsafe { take_c_string(ffi::mobi_meta_get_isbn(self.handle)) }
    }

    /// Subject / genre string from EXTH. Returns a single combined string;
    /// callers that want a list should split on `;` or `,`.
    pub fn subject(&self) -> Option<String> {
        unsafe { take_c_string(ffi::mobi_meta_get_subject(self.handle)) }
    }

    /// Whether the active content is KF8 (AZW3) rather than legacy
    /// Mobipocket. Hybrid files with both halves still report `true` here
    /// because the KF8 half is preferred.
    pub fn is_kf8(&self) -> bool {
        // SAFETY: `handle` is valid for the lifetime of `self`; the
        // function only reads the struct.
        unsafe { ffi::mobi_is_kf8(self.handle) }
    }

    /// File-format version reported by libmobi. Legacy Mobipocket is
    /// version 6; KF8/AZW3 is version 8.
    pub fn file_version(&self) -> usize {
        // SAFETY: as above.
        unsafe { ffi::mobi_get_fileversion(self.handle) }
    }

    /// Reconstruct the rawml view: markup parts (HTML), flow parts (CSS/SVG),
    /// and resource parts (images/fonts). For legacy Mobipocket there is a
    /// single markup part; KF8 yields one part per chunked HTML file.
    ///
    /// The returned [`MobiRawml`] borrows from `self`, so the book must
    /// outlive it.
    pub fn rawml(&self) -> FolioResult<MobiRawml<'_>> {
        // libmobi splits allocation and parsing: `mobi_init_rawml` only
        // allocates and zero-initializes the struct, `mobi_parse_rawml` is
        // what populates markup/flow/resources. Calling only the first gives
        // a non-null handle with empty part lists.
        //
        // SAFETY: `mobi_init_rawml` returns either null (OOM) or a heap-
        // allocated `MOBIRawml` that we own via `MobiRawml`'s Drop. On
        // parse failure we free it immediately to avoid a leak.
        let ptr = unsafe { ffi::mobi_init_rawml(self.handle) };
        let ptr = NonNull::new(ptr)
            .ok_or_else(|| FolioError::Internal("libmobi failed to allocate rawml".into()))?;
        let rc = unsafe { ffi::mobi_parse_rawml(ptr.as_ptr(), self.handle) };
        if rc != ffi::MOBI_RET_MOBI_SUCCESS {
            unsafe { ffi::mobi_free_rawml(ptr.as_ptr()) };
            return Err(map_mobi_ret(rc, "libmobi failed to parse rawml"));
        }
        Ok(MobiRawml {
            ptr,
            _phantom: PhantomData,
        })
    }

    /// Extract the full-size cover image. Returns `None` if the book has
    /// no EXTH cover record or the referenced PDB record is missing/empty.
    ///
    /// The returned slice borrows from the underlying `MOBIData`, so the
    /// book must outlive the cover.
    pub fn cover(&self) -> Option<MobiCover<'_>> {
        // SAFETY: libmobi returns either null or a pointer into `MOBIData`'s
        // own EXTH/record storage. We only dereference after null-checking
        // and treat the data as a shared borrow for `&self`'s lifetime.
        unsafe {
            let exth =
                ffi::mobi_get_exthrecord_by_tag(self.handle, ffi::MOBIExthTag_EXTH_COVEROFFSET);
            if exth.is_null() {
                return None;
            }
            let exth_ref = &*exth;
            if exth_ref.data.is_null() || exth_ref.size == 0 {
                return None;
            }
            let offset =
                ffi::mobi_decode_exthvalue(exth_ref.data as *const _, exth_ref.size as usize);
            let first = ffi::mobi_get_first_resource_record(self.handle);
            let seq = first.checked_add(offset as usize)?;
            let rec = ffi::mobi_get_record_by_seqnumber(self.handle, seq);
            if rec.is_null() {
                return None;
            }
            let rec_ref = &*rec;
            if rec_ref.data.is_null() || rec_ref.size == 0 {
                return None;
            }
            let data = slice::from_raw_parts(rec_ref.data, rec_ref.size);
            // Refuse to label unknown bytes as an image. A malformed EXTH
            // coveroffset can point at arbitrary records (audio, HTML text,
            // garbage); surfacing those as `cover.jpg` would poison the
            // cover cache and confuse downstream MIME handling. None is the
            // honest answer when magic bytes don't match a known raster.
            let extension = detect_image_ext(data)?;
            Some(MobiCover { data, extension })
        }
    }
}

impl Drop for MobiBook {
    fn drop(&mut self) {
        if !self.handle.is_null() {
            // SAFETY: `handle` came from `mobi_init` and we haven't freed
            // it elsewhere.
            unsafe { ffi::mobi_free(self.handle) };
            self.handle = ptr::null_mut();
        }
    }
}

/// Cover image extracted from the EXTH metadata. The slice borrows from the
/// owning [`MobiBook`].
pub struct MobiCover<'a> {
    /// Raw image bytes as stored in the MOBI record (no re-encoding).
    pub data: &'a [u8],
    /// File extension (`"jpg"`, `"png"`, `"gif"`, `"bmp"`), detected by magic
    /// bytes. Defaults to `"jpg"` for unrecognized signatures, which matches
    /// the overwhelmingly common case for Kindle covers.
    pub extension: &'static str,
}

/// Reconstructed rawml view: markup / flow / resource parts. Borrows from the
/// owning [`MobiBook`] and frees the underlying `MOBIRawml` on drop.
pub struct MobiRawml<'a> {
    ptr: NonNull<ffi::MOBIRawml>,
    _phantom: PhantomData<&'a MobiBook>,
}

impl MobiRawml<'_> {
    /// Whether this rawml was reconstructed from the KF8 half.
    pub fn is_kf8(&self) -> bool {
        // SAFETY: `ptr` is non-null by construction.
        unsafe { ffi::mobi_is_rawml_kf8(self.ptr.as_ptr()) }
    }

    /// Iterate markup parts (HTML for every ebook, one per KF8 chunked file
    /// or a single blob for legacy Mobipocket).
    pub fn parts(&self) -> PartIter<'_> {
        // SAFETY: `ptr` is non-null; we read the `markup` head pointer and
        // walk the linked list through `next`.
        PartIter::new(unsafe { self.ptr.as_ref().markup })
    }

    /// Iterate flow parts (CSS, SVG). KF8-only; empty for legacy Mobipocket.
    pub fn flows(&self) -> PartIter<'_> {
        PartIter::new(unsafe { self.ptr.as_ref().flow })
    }

    /// Iterate resource parts (images, fonts). In KF8 files the cover may
    /// also be present here; the canonical cover lookup is
    /// [`MobiBook::cover`].
    pub fn resources(&self) -> PartIter<'_> {
        PartIter::new(unsafe { self.ptr.as_ref().resources })
    }
}

impl Drop for MobiRawml<'_> {
    fn drop(&mut self) {
        // SAFETY: `ptr` came from `mobi_init_rawml` and hasn't been freed.
        unsafe { ffi::mobi_free_rawml(self.ptr.as_ptr()) };
    }
}

/// One entry in a rawml linked list (`markup`, `flow`, or `resources`).
/// The `data` slice borrows from the owning [`MobiRawml`].
pub struct MobiPart<'a> {
    /// Stable identifier assigned by libmobi. For KF8 this matches the
    /// numeric FID used in `kindle:flow:XXXX` / `kindle:embed:XXXX`
    /// references inside the HTML.
    pub uid: usize,
    pub kind: PartKind,
    pub data: &'a [u8],
}

/// Linked-list iterator over `MOBIPart` nodes.
pub struct PartIter<'a> {
    current: *mut ffi::MOBIPart,
    _phantom: PhantomData<&'a MobiRawml<'a>>,
}

impl<'a> PartIter<'a> {
    fn new(head: *mut ffi::MOBIPart) -> Self {
        Self {
            current: head,
            _phantom: PhantomData,
        }
    }
}

impl<'a> Iterator for PartIter<'a> {
    type Item = MobiPart<'a>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.current.is_null() {
            return None;
        }
        // SAFETY: `current` is non-null and points into the MOBIPart list
        // owned by `MobiRawml`, which outlives our borrow.
        let part = unsafe { &*self.current };
        self.current = part.next;
        let data = if part.data.is_null() || part.size == 0 {
            &[][..]
        } else {
            // SAFETY: libmobi owns `data` for `size` bytes; the borrow is
            // scoped to `'a` which does not outlive the `MobiRawml`.
            unsafe { slice::from_raw_parts(part.data, part.size) }
        };
        Some(MobiPart {
            uid: part.uid,
            kind: PartKind::from_filetype(part.type_),
            data,
        })
    }
}

/// Content type of a rawml part, matching libmobi's `MOBIFiletype` enum.
/// Unknown values land in [`PartKind::Other`] so forward-compat additions
/// on the libmobi side don't silently disappear.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PartKind {
    Html,
    Css,
    Svg,
    Opf,
    Ncx,
    Jpg,
    Gif,
    Png,
    Bmp,
    Otf,
    Ttf,
    Other(u32),
}

impl PartKind {
    fn from_filetype(ft: ffi::MOBIFiletype) -> Self {
        #[allow(non_upper_case_globals)]
        match ft {
            ffi::MOBIFiletype_T_HTML => Self::Html,
            ffi::MOBIFiletype_T_CSS => Self::Css,
            ffi::MOBIFiletype_T_SVG => Self::Svg,
            ffi::MOBIFiletype_T_OPF => Self::Opf,
            ffi::MOBIFiletype_T_NCX => Self::Ncx,
            ffi::MOBIFiletype_T_JPG => Self::Jpg,
            ffi::MOBIFiletype_T_GIF => Self::Gif,
            ffi::MOBIFiletype_T_PNG => Self::Png,
            ffi::MOBIFiletype_T_BMP => Self::Bmp,
            ffi::MOBIFiletype_T_OTF => Self::Otf,
            ffi::MOBIFiletype_T_TTF => Self::Ttf,
            other => Self::Other(other),
        }
    }

    /// Whether this part is a raster image (JPEG/PNG/GIF/BMP).
    pub fn is_image(&self) -> bool {
        matches!(self, Self::Jpg | Self::Gif | Self::Png | Self::Bmp)
    }

    /// Conventional file extension for writing to disk or building keys.
    /// `None` for unrecognized types.
    pub fn extension(&self) -> Option<&'static str> {
        Some(match self {
            Self::Html => "html",
            Self::Css => "css",
            Self::Svg => "svg",
            Self::Opf => "opf",
            Self::Ncx => "ncx",
            Self::Jpg => "jpg",
            Self::Gif => "gif",
            Self::Png => "png",
            Self::Bmp => "bmp",
            Self::Otf => "otf",
            Self::Ttf => "ttf",
            Self::Other(_) => return None,
        })
    }

    /// MIME type suitable for `Content-Type` headers or `data:` URIs.
    /// `None` for unrecognized types.
    pub fn mime_type(&self) -> Option<&'static str> {
        Some(match self {
            Self::Html => "text/html",
            Self::Css => "text/css",
            Self::Svg => "image/svg+xml",
            Self::Opf => "application/oebps-package+xml",
            Self::Ncx => "application/x-dtbncx+xml",
            Self::Jpg => "image/jpeg",
            Self::Gif => "image/gif",
            Self::Png => "image/png",
            Self::Bmp => "image/bmp",
            Self::Otf => "font/otf",
            Self::Ttf => "font/ttf",
            Self::Other(_) => return None,
        })
    }
}

/// Detect raster-image extension from magic bytes. Returns `None` for
/// unknown signatures (the caller decides the fallback).
fn detect_image_ext(data: &[u8]) -> Option<&'static str> {
    match data {
        [0xFF, 0xD8, 0xFF, ..] => Some("jpg"),
        [0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A, ..] => Some("png"),
        [b'G', b'I', b'F', b'8', _, b'a', ..] => Some("gif"),
        [b'B', b'M', ..] => Some("bmp"),
        _ => None,
    }
}

/// Translate a libmobi `MOBI_RET` code to a [`FolioError`] preserving the
/// semantic category. Keeps the raw code in the message so the original
/// libmobi failure is still visible in logs.
fn map_mobi_ret(rc: ffi::MOBI_RET, context: &str) -> FolioError {
    let msg = format!("{context}: libmobi code {rc}");
    match rc {
        ffi::MOBI_RET_MOBI_FILE_NOT_FOUND => FolioError::NotFound(msg),
        ffi::MOBI_RET_MOBI_FILE_ENCRYPTED
        | ffi::MOBI_RET_MOBI_FILE_UNSUPPORTED
        | ffi::MOBI_RET_MOBI_DATA_CORRUPT
        | ffi::MOBI_RET_MOBI_XML_ERR
        | ffi::MOBI_RET_MOBI_BUFFER_END
        | ffi::MOBI_RET_MOBI_PARAM_ERR
        | ffi::MOBI_RET_MOBI_DRM_PIDINV
        | ffi::MOBI_RET_MOBI_DRM_KEYNOTFOUND
        | ffi::MOBI_RET_MOBI_DRM_UNSUPPORTED
        | ffi::MOBI_RET_MOBI_DRM_EXPIRED => FolioError::InvalidInput(msg),
        ffi::MOBI_RET_MOBI_MALLOC_FAILED
        | ffi::MOBI_RET_MOBI_INIT_FAILED
        | ffi::MOBI_RET_MOBI_WRITE_FAILED
        | ffi::MOBI_RET_MOBI_DRM_RANDOM_ERR
        | ffi::MOBI_RET_MOBI_ERROR => FolioError::Internal(msg),
        _ => FolioError::Internal(msg),
    }
}

/// Consume a heap-allocated C string from libmobi, returning an owned
/// `String` and calling `libc::free` so the memory isn't leaked.
///
/// # Safety
/// `ptr` must be either null or a valid pointer that libmobi produced via
/// `malloc`/`strdup`. Ownership transfers into this function.
unsafe fn take_c_string(ptr: *mut std::os::raw::c_char) -> Option<String> {
    if ptr.is_null() {
        return None;
    }
    let owned = CStr::from_ptr(ptr).to_string_lossy().into_owned();
    // libmobi allocates with malloc and documents that callers must free
    // the returned buffers. We release it here.
    extern "C" {
        fn free(ptr: *mut std::os::raw::c_void);
    }
    free(ptr as *mut _);
    Some(owned)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn fixture(name: &str) -> Option<PathBuf> {
        // The workspace layout puts fixtures in src-tauri/test-fixtures/
        // (gitignored). Folio-core is built from the workspace root, so
        // CARGO_MANIFEST_DIR points to folio-core/.
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("src-tauri")
            .join("test-fixtures")
            .join(name);
        path.exists().then_some(path)
    }

    #[test]
    fn opens_legacy_mobi_and_reads_title() {
        let Some(path) = fixture("alice-legacy.mobi") else {
            eprintln!("skipping: alice-legacy.mobi not present");
            return;
        };
        let book = MobiBook::open(&path).expect("open legacy MOBI");
        let title = book.title().expect("read title");
        assert!(
            title.to_lowercase().contains("alice"),
            "expected 'Alice' in title, got {title:?}"
        );
        let author = book.author().expect("read author");
        assert!(
            author.to_lowercase().contains("carroll"),
            "expected 'Carroll' in author, got {author:?}"
        );
        assert!(
            !book.is_kf8(),
            "legacy Mobipocket must not be reported as KF8"
        );
        assert_eq!(
            book.file_version(),
            6,
            "legacy Mobipocket is file version 6"
        );
    }

    #[test]
    fn opens_kf8_mobi_and_reads_title() {
        let Some(path) = fixture("alice.mobi") else {
            eprintln!("skipping: alice.mobi not present");
            return;
        };
        let book = MobiBook::open(&path).expect("open KF8 MOBI");
        let title = book.title().expect("read title");
        assert!(
            title.to_lowercase().contains("alice"),
            "expected 'Alice' in title, got {title:?}"
        );
        let author = book.author().expect("read author");
        assert!(
            author.to_lowercase().contains("carroll"),
            "expected 'Carroll' in author, got {author:?}"
        );
        assert!(book.is_kf8(), "AZW3 file must be detected as KF8");
        assert_eq!(book.file_version(), 8, "AZW3/KF8 is file version 8");
    }

    #[test]
    fn rawml_yields_html_and_images_for_legacy_mobi() {
        let Some(path) = fixture("alice-legacy.mobi") else {
            eprintln!("skipping: alice-legacy.mobi not present");
            return;
        };
        let book = MobiBook::open(&path).expect("open legacy MOBI");
        let rawml = book.rawml().expect("reconstruct rawml");
        assert!(!rawml.is_kf8(), "legacy rawml must not report KF8");

        let html_parts: Vec<_> = rawml
            .parts()
            .filter(|p| matches!(p.kind, PartKind::Html))
            .collect();
        assert!(
            !html_parts.is_empty(),
            "legacy MOBI should have at least one HTML markup part"
        );
        assert!(
            html_parts.iter().any(|p| !p.data.is_empty()),
            "at least one HTML part should carry bytes"
        );

        let images: Vec<_> = rawml.resources().filter(|p| p.kind.is_image()).collect();
        assert!(
            !images.is_empty(),
            "alice-legacy.mobi ships with illustrations — expected image resources"
        );
        assert!(images.iter().all(|p| !p.data.is_empty()));
    }

    #[test]
    fn rawml_yields_html_and_images_for_kf8_mobi() {
        let Some(path) = fixture("alice.mobi") else {
            eprintln!("skipping: alice.mobi not present");
            return;
        };
        let book = MobiBook::open(&path).expect("open KF8 MOBI");
        let rawml = book.rawml().expect("reconstruct rawml");
        assert!(rawml.is_kf8(), "KF8 rawml must report KF8");

        // KF8 splits HTML into per-file chunks (via SKEL/FRAG indexes), so
        // we expect multiple markup parts — not the single blob legacy
        // Mobipocket produces.
        let html_parts: Vec<_> = rawml
            .parts()
            .filter(|p| matches!(p.kind, PartKind::Html))
            .collect();
        assert!(
            html_parts.len() > 1,
            "KF8 MOBI should split HTML into multiple markup parts, got {}",
            html_parts.len()
        );
        assert!(html_parts.iter().all(|p| !p.data.is_empty()));

        // Flows are KF8-only and typically carry CSS reconstructed from
        // inline style tags.
        let css_flows = rawml
            .flows()
            .filter(|p| matches!(p.kind, PartKind::Css))
            .count();
        assert!(
            css_flows > 0,
            "KF8 alice.mobi should expose at least one CSS flow"
        );

        let images: Vec<_> = rawml.resources().filter(|p| p.kind.is_image()).collect();
        assert!(
            !images.is_empty(),
            "alice.mobi ships with illustrations — expected image resources"
        );
    }

    #[test]
    fn cover_extraction_returns_jpeg_for_alice() {
        let Some(path) = fixture("alice.mobi") else {
            eprintln!("skipping: alice.mobi not present");
            return;
        };
        let book = MobiBook::open(&path).expect("open KF8 MOBI");
        let cover = book.cover().expect("alice.mobi has an EXTH cover");
        assert!(!cover.data.is_empty(), "cover data must be non-empty");
        assert!(
            matches!(cover.extension, "jpg" | "png" | "gif" | "bmp"),
            "expected a known image extension, got {:?}",
            cover.extension
        );
        // Canonical JPEG magic for Project Gutenberg MOBI covers.
        if cover.extension == "jpg" {
            assert_eq!(&cover.data[..3], b"\xFF\xD8\xFF");
        }
    }

    #[test]
    fn part_kind_helpers() {
        assert!(PartKind::Jpg.is_image());
        assert!(!PartKind::Html.is_image());
        assert_eq!(PartKind::Png.extension(), Some("png"));
        assert_eq!(PartKind::Png.mime_type(), Some("image/png"));
        assert_eq!(PartKind::Other(42).extension(), None);
    }

    #[test]
    fn map_mobi_ret_categorizes_codes() {
        assert_eq!(
            map_mobi_ret(ffi::MOBI_RET_MOBI_FILE_NOT_FOUND, "x").kind(),
            "NotFound"
        );
        assert_eq!(
            map_mobi_ret(ffi::MOBI_RET_MOBI_FILE_ENCRYPTED, "x").kind(),
            "InvalidInput"
        );
        assert_eq!(
            map_mobi_ret(ffi::MOBI_RET_MOBI_FILE_UNSUPPORTED, "x").kind(),
            "InvalidInput"
        );
        assert_eq!(
            map_mobi_ret(ffi::MOBI_RET_MOBI_DATA_CORRUPT, "x").kind(),
            "InvalidInput"
        );
        assert_eq!(
            map_mobi_ret(ffi::MOBI_RET_MOBI_MALLOC_FAILED, "x").kind(),
            "Internal"
        );
        assert_eq!(
            map_mobi_ret(ffi::MOBI_RET_MOBI_INIT_FAILED, "x").kind(),
            "Internal"
        );
        assert_eq!(
            map_mobi_ret(ffi::MOBI_RET_MOBI_ERROR, "x").kind(),
            "Internal"
        );
        // Raw code is preserved in the message for debuggability.
        let err = map_mobi_ret(ffi::MOBI_RET_MOBI_DATA_CORRUPT, "open foo");
        assert!(err.to_string().contains("open foo"));
        assert!(err
            .to_string()
            .contains(&format!("{}", ffi::MOBI_RET_MOBI_DATA_CORRUPT)));
    }

    #[test]
    fn open_missing_file_returns_not_found() {
        let result = MobiBook::open(Path::new("/definitely/does/not/exist.mobi"));
        match result {
            Ok(_) => panic!("expected open() to fail for a non-existent path"),
            Err(err) => assert_eq!(err.kind(), "NotFound"),
        }
    }

    #[test]
    fn cover_returns_none_when_magic_bytes_unknown() {
        // This is a unit-level check that the refactor held: without an
        // actual book we can only exercise `detect_image_ext`.
        assert_eq!(detect_image_ext(b"RIFFxxxxWEBP"), None);
        assert_eq!(detect_image_ext(b"<!DOCTYPE html>"), None);
    }

    #[test]
    fn detect_image_ext_matches_known_signatures() {
        assert_eq!(
            detect_image_ext(&[0xFF, 0xD8, 0xFF, 0xE0, 0x00]),
            Some("jpg")
        );
        assert_eq!(
            detect_image_ext(b"\x89PNG\r\n\x1a\n\x00\x00\x00\x0D"),
            Some("png")
        );
        assert_eq!(detect_image_ext(b"GIF89a...."), Some("gif"));
        assert_eq!(detect_image_ext(b"GIF87a...."), Some("gif"));
        assert_eq!(detect_image_ext(b"BM\x00\x00"), Some("bmp"));
        assert_eq!(detect_image_ext(b"abcdef"), None);
        assert_eq!(detect_image_ext(&[]), None);
    }
}
